/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: ["./app/**/*.{js,jsx,ts,tsx}", "./components/**/*.{js,jsx,ts,tsx}"],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      colors: {
        primary: "#2c694e",
        "primary-dim": "#1e5d43",
        "primary-container": "#b1f0ce",
        "primary-fixed-dim": "#a3e2c0",
        "on-primary": "#e1ffec",
        "on-primary-container": "#1d5c42",
        secondary: "#5d605d",
        "secondary-container": "#e1e3df",
        "on-secondary": "#f8f9f5",
        "on-secondary-container": "#4f5250",
        tertiary: "#596342",
        "tertiary-container": "#eef9cd",
        "on-tertiary": "#f3fed3",
        "on-tertiary-container": "#56603f",
        surface: "#f8f9fa",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f1f4f6",
        "surface-container": "#eaeff1",
        "surface-container-high": "#e3e9ec",
        "surface-container-highest": "#dbe4e7",
        "on-surface": "#2b3437",
        "on-surface-variant": "#586064",
        background: "#f8f9fa",
        "on-background": "#2b3437",
        outline: "#737c7f",
        "outline-variant": "#abb3b7",
        error: "#9f403d",
        "error-container": "#fe8983",
        "on-error": "#fff7f6",
      },
    },
  },
  plugins: [],
};
